### ISSUE TITLE
How to use and run on UBUNTU

### ISSUE THREAD

**Issue by v3nk1** [dmdedup/dmdedup#14]
Hi all, 
I am trying to do some IO operation on disk, which surely have no duplicated data whilst storing to disk. Here is the info
I am able to compile module, inserted the module on OS running linux-4.4 kernel. Afterward did create dmsetup create mydedup and i am able to see /dev/mapper/mydedup and /dev/dm-0 device nodes. Then how to perform data operations? I tried mounting mydedup block device like this,
# mount /dev/mapper/mydedup /mnt

It fails with error no filesystem, even tried /dev/dm-0 and /dev/sdbX also.
Appreciate any points.

Thanks in advance,
Venkatesh.

**Comment by venkrishraja** [comment]
Did u format a new filesystem on mydedup? Like this:

> mkfs -t ext4 dev/mapper/mydedup

The did u mention what filesystem u want? Like this : 

> mount -t ext4 /dev/mapper/mydedup /mnt

**Comment by v3nk1** [comment]
Yeah, I did try that, but question here is, did it end up **deduplicating filesystem** installing(metadata like supernode, inode, structure) also? Since in driver we are just checking data, irrespective of anything.
currently I am using **dd** for I/O operations.

**Comment by venkrishraja** [comment]
No your question was 

> It fails with error no filesystem, even tried /dev/dm-0 and /dev/sdbX also.

Has that been resolved?

**Comment by v3nk1** [comment]
Yeah, It was resolved. But my question still stands.. When i was using **dm** with filesystem installed, I see more dupwrites and writes than the data actually being copied. So It should not be like that, Right??
Suppose Lets assume i copy a file of 4096Bytes to mount point, it should increment write by 1(4K block). It is not happening as i showed but it increments more than 1. Why??

**Comment by sectorsize512** [comment]
Hey, not sure you still need this answer, but dmdedup dedups all writes that go to it: file-system data, metadata, journal, etc.

**Comment by sectorsize512** [comment]
v3nk1, any updates on this, or should we close the ticket? Thanks!

**Comment by v3nk1** [comment]
Thanks for response. Is it a correct behavior that, dmdedup duplicates file system installation data also like inode and superbolck info also??

**Comment by sectorsize512** [comment]
Yes, at this point it deduplicates everything. But in the future, we plan to avoid this. Here is corresponding paper:

https://www.usenix.org/conference/fast16/technical-sessions/presentation/mandal

Vasily

**Comment by sectorsize512** [comment]
Closing the issue as it seems to be resolved. Reopen if needed.
