### ISSUE TITLE
How to configure cache size?

### ISSUE THREAD

**Issue by Oliver-Luo** [dmdedup/dmdedup#17]
Hi, there. I'm interested in dmdedup and got it installed on my system. However, I got a question here:

How to configure the cache size of the cow-b-tree metadata backend? The only way that looks possible for me is that the variable METADATA_CACHESIZE defined in dm-dedup-cbt.c, but the comment said currently block manager ignores this value. And in persistent-data/dm-block-manager.c, function dm_block_manager_create() do ignore the parameter "cache_size".

Maybe I should change the setting of bufio directly? Cause I see the memory used by bufio is defined in following statements:

Linux/drivers/md/dm-bufio.c:
`#define DM_BUFIO_MIN_BUFFERS            8`
`#define DM_BUFIO_MEMORY_PERCENT         2`
`#define DM_BUFIO_VMALLOC_PERCENT        25`
`#define DM_BUFIO_WRITEBACK_PERCENT      75`

Thanks~

**Comment by sectorsize512** [comment]
Hi,

You are right, the function which we pass METADATA_CACHESIZE to - `dm_block_manager_create()` - ignores `cache_size` argument in 3.19 kernel. (I suspect the idea was that it will be used in the future.)
At this point you can control cache size via the `max_cache_size_bytes` parameter of `dm-bufio` kernel module. I.e., when you load this module, set this parameter to the value that you want. (I think at this point it is computed as 2% of the memory available or something along these lines).

HTH,
Vasily

**Comment by Oliver-Luo** [comment]
Thanks for your answer~
