### ISSUE TITLE
dmdedup cannot be compiled on kernels >4.4

### ISSUE THREAD

**Issue by uzytkownik** [dmdedup/dmdedup#39]
`dm_bm_unlock` no longer returns int - it returns void since 4.4. I run into other problems on 4.9 as well.

**Comment by vinothkumarraja** [comment]
Hi,
We are planning to create a separate repository for kernels > 4.x. The code in this repository has been tested only until 3.19

**Comment by uzytkownik** [comment]
@vinothkumarraja any plans to upstream it?

**Comment by vinothkumarraja** [comment]
Hi,
We have the working code for kernel 4.8 in our private repository. We ll make it public by end of the week.

**Comment by vinothkumarraja** [comment]
We have created a separate repository for >4.8 and made it public. 
You can find the info here https://github.com/dmdedup
