### ISSUE TITLE
dmdedup is not de-duplicating data with ext4fs

### ISSUE THREAD

**Issue by venktesh-bolla** [dmdedup/dmdedup#43]
Hi folks,

Found predominent issue with dmdedup.
If I do IO on ext4 fs installed dmtarget mount point, I am not seeing any disk saving after copying same data file twice.
Prerequisites: 10GB random file (from /dev/urandom)

Steps to reproduce the issue:
----------------------------------------
$ ls -l randomfile.10G
-rw-r--r-- 1 root root 10737418240 Apr 18 10:26 randomfile.10G

$ dmsetup status
mydedup: 0 732592680 dedup 61049390 61049390 0 0 4096 8:1 1:0 0 0 0 0 0 0 0 last used pbn: 0
$ mkfs.ext4 /dev/mapper/mydedup
$ dmsetup status
mydedup: 0 732592680 dedup 61049390 61048336 1054 34362 4096 8:1 1:0 34363 1054 33309 0 1 34362 0 last used pbn: 1053
$ mount /dev/mapper/mydedup /mnt
$ df -l
Filesystem          1K-blocks      Used       Available Use%    Mounted on
/dev/root           203289800 169926452  23013764  89%    /
devtmpfs             16688000         0          16688000   0%    /dev
tmpfs                   16688576         0          16688576   0%    /dev/shm
tmpfs                   16688576    119744     16568832   1%    /run
tmpfs                           5120         0                  5120   0%    /run/lock
tmpfs                   16688576         0          16688576   0%    /sys/fs/cgroup
tmpfs                     3337728          0           3337728   0%    /run/user/0
/dev/mapper/mydedup 360417164     68160 342017804   1% /mnt

$ cp randomfile.10G /mnt/r1
$ dmsetup status
mydedup: 0 732592680 dedup 61049390 58426253 2623137 4086923 4096 8:1 1:0 4087690 2623137 1464553 0 767 4086923 0 last used pbn: 2623136

$ df -l
Filesystem          1K-blocks      Used           Available Use% Mounted on
/dev/root              203289800 169926680  23013536  89%   /
devtmpfs                16688000         0         16688000   0%    /dev
tmpfs                      16688576         0         16688576   0%    /dev/shm
tmpfs                      16688576    127936    16560640   1%   /run
tmpfs                              5120         0                 5120   0%   /run/lock
tmpfs                      16688576         0         16688576   0%   /sys/fs/cgroup
tmpfs                        3337728         0           3337728   0%   /run/user/0
/dev/mapper/mydedup 360417164  10553924 331532040   4% /mnt

$ cp randomfile.10G /mnt/r2
$ dmsetup status
mydedup: 0 732592680 dedup 61049390 58426215 2623175 6708444 4096 8:1 1:0 6709338 2623175 4086163 0 894 6708444 0 last used pbn: 2623174

$ df -l
Filesystem          1K-blocks      Used        Available  Use% Mounted on
/dev/root           203289800  169926728  23013488  89%  /
devtmpfs             16688000                 0  16688000   0%  /dev
tmpfs                16688576                    0  16688576   0%  /dev/shm
tmpfs                16688576          127936  16560640   1%  /run
tmpfs                    5120                        0      5120       0%  /run/lock
tmpfs                16688576                    0  16688576   0%  /sys/fs/cgroup
tmpfs                 3337728                     0   3337728    0%  /run/user/0
/dev/mapper/mydedup 360417164  21039688 321046276   7% /mnt

$ ls -lh /mnt
total 21G
drwx------ 2 root root 16K May 14 15:58 lost+found
-rw-r--r-- 1 root root 10G May 14 16:11 r1
-rw-r--r-- 1 root root 10G May 14 17:46 r1-dup

In above dmsetup stats, it is showing 95% data is deduplicated, but eventually it is not saving any disk space in "df -l"

What am i missing???

Venkatesh B.

**Comment by vinothkumarraja** [comment]
Hi Venkatesh,

Since we are deduplicating data in the device level, the file system has no way of figuring out the exact disk space. The actual disk usage can be only be found by dmsetup status command.

Please let us know if you are unable to write to the device even when there is free space according to dmsetup status's output.

Also I'm wondering if you are experiencing different behavior with other file systems (say for example ext3) which made you raise this issue. 

Thanks,
Vinothkumar Raja
